//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_Backup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BACKUP_HISTORY {
            get {
                return ((int)(this["BACKUP_HISTORY"]));
            }
            set {
                this["BACKUP_HISTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DURATION_INDEX {
            get {
                return ((byte)(this["DURATION_INDEX"]));
            }
            set {
                this["DURATION_INDEX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte TIME_INTERVAL_HOURS {
            get {
                return ((byte)(this["TIME_INTERVAL_HOURS"]));
            }
            set {
                this["TIME_INTERVAL_HOURS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte TIME_INTERVAL_MINUTES {
            get {
                return ((byte)(this["TIME_INTERVAL_MINUTES"]));
            }
            set {
                this["TIME_INTERVAL_MINUTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte TIME_INTERVAL_SECONDS {
            get {
                return ((byte)(this["TIME_INTERVAL_SECONDS"]));
            }
            set {
                this["TIME_INTERVAL_SECONDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FOLDER_TO_BACKUP {
            get {
                return ((string)(this["FOLDER_TO_BACKUP"]));
            }
            set {
                this["FOLDER_TO_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FOLDER_TO_SAVE {
            get {
                return ((string)(this["FOLDER_TO_SAVE"]));
            }
            set {
                this["FOLDER_TO_SAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTOSTART {
            get {
                return ((bool)(this["AUTOSTART"]));
            }
            set {
                this["AUTOSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150")]
        public global::System.Drawing.Point WINDOW_POSITION {
            get {
                return ((global::System.Drawing.Point)(this["WINDOW_POSITION"]));
            }
            set {
                this["WINDOW_POSITION"] = value;
            }
        }
    }
}
